apiVersion: v1
kind: Namespace
metadata:
    name: quantumnest-prod
    labels:
        name: quantumnest-prod
        environment: production
        compliance: pci-dss-sox-gdpr
---
apiVersion: v1
kind: Namespace
metadata:
    name: quantumnest-staging
    labels:
        name: quantumnest-staging
        environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
    name: quantumnest-dev
    labels:
        name: quantumnest-dev
        environment: development
