apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-backend-sa
    namespace: quantumnest-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: quantumnest-backend-role
    namespace: quantumnest-prod
rules:
    - apiGroups: ['']
      resources: ['configmaps', 'secrets']
      verbs: ['get', 'list', 'watch']
    - apiGroups: ['']
      resources: ['pods']
      verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: quantumnest-backend-rolebinding
    namespace: quantumnest-prod
subjects:
    - kind: ServiceAccount
      name: quantumnest-backend-sa
      namespace: quantumnest-prod
roleRef:
    kind: Role
    name: quantumnest-backend-role
    apiGroup: rbac.authorization.k8s.io
